feat: Open files

diff --git a/.github/workflows/dart.yml b/.github/workflows/dart.yml
--- a/.github/workflows/dart.yml
+++ b/.github/workflows/dart.yml
@@ -1,8 +1,3 @@
-# This workflow uses actions that are not certified by GitHub.
-# They are provided by a third-party and are governed by
-# separate terms of service, privacy policy, and support
-# documentation.
-
 name: Dart 
 
 on:
@@ -27,9 +22,7 @@ jobs:
 
     steps:
       - uses: actions/checkout@v3
-
       - uses: subosito/flutter-action@v2
-
       - name: Install dependencies
         run: dart pub get
 
@@ -38,20 +31,39 @@ jobs:
 
       - name: Execute golden Tests
         run: |
-          set +e  # Desabilitar saída imediata por erros
+          set +e
           flutter test test/golden/home_screen_test.dart --dart-define="color=${{ github.event.inputs.color }}" --dart-define="text=${{ github.event.inputs.text }}" --dart-define="alignment=${{ github.event.inputs.alignment }}"
-          status=$?  # Salvar resultado da execução
-
+          status=$?
           if [ "$status" -ne 0 ]; then
-            echo "Erro! Check images differences. Exit code: $status"
-            cp -r test/golden_test_output/* golden_output/  # Corrige o caminho de destino
+            echo "Error! Check images differences. Exit code: $status"
+            cp -r test/golden_test_output/* golden_output/
           fi
-
           echo "Finish Workflow"
 
-      - name: Enviar screenshots (se teste bem-sucedido)
+      - name: Save files
         uses: actions/upload-artifact@v3
         with:
           name: golden-test-screenshots
-          path: golden_output  # Corrigi o caminho da origem
-          if: success()
+          path: test/golden_test_output
+
+      - name: Get files URL
+        uses: github/actions/get-artifact-url@v2
+        with:
+          name: golden-test-screenshots
+          path: |
+            golden-test-screenshots/.artifact
+          event: ${{ github.event }}
+
+      - name: Open files
+        uses: actions/github-script@v5
+        with:
+          github-token: ${{ secrets.GITHUB_TOKEN }}
+          script: |
+            const url = '${{ steps.get-artifact-url.outputs.url }}';
+            const window = require('electron').remote.getCurrentWindow();
+            window.open(url, {
+              show: true,
+              newWindow: true,
+              resizable: true,
+              maximizable: true
+            });
